// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210630143128_Added Check Constraint for Fantasy Team Goalie One")]
    partial class AddedCheckConstraintforFantasyTeamGoalieOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("APIFootballID")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Domain.FantasyLeague", b =>
                {
                    b.Property<Guid>("FantasyLeagueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LeagueCaption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueLogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Default League Logo");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTeams")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.HasKey("FantasyLeagueID");

                    b.ToTable("FantasyLeagues");
                });

            modelBuilder.Entity("Domain.FantasyLeagueAdmin", b =>
                {
                    b.Property<Guid>("FantasyLeagueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FantasyLeagueID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("FantasyLeaguesAdmins");
                });

            modelBuilder.Entity("Domain.FantasyLeagueTeams", b =>
                {
                    b.Property<Guid>("FantasyLeagueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FantasyTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FantasyLeagueID", "FantasyTeamID");

                    b.HasIndex("FantasyTeamID");

                    b.ToTable("FantasyLeagueTeams");
                });

            modelBuilder.Entity("Domain.FantasyTeam", b =>
                {
                    b.Property<Guid>("FantasyTeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DefenderFiveID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefenderFourID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefenderOneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefenderThreeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefenderTwoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FantasyTeamLogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Hello World, This  is an image");

                    b.Property<string>("FantasyTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ForwardOneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ForwardThreeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ForwardTwoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoalieOneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoalieTwoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MidfielderFiveID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MidfielderFourID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MidfielderOneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MidfielderThreeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MidfielderTwoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MoneyBalance")
                        .HasColumnType("float");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlayerID1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FantasyTeamID");

                    b.HasIndex("DefenderFiveID");

                    b.HasIndex("DefenderFourID");

                    b.HasIndex("DefenderOneID");

                    b.HasIndex("DefenderThreeID");

                    b.HasIndex("DefenderTwoID");

                    b.HasIndex("ForwardOneID");

                    b.HasIndex("ForwardThreeID");

                    b.HasIndex("ForwardTwoID");

                    b.HasIndex("GoalieOneID");

                    b.HasIndex("GoalieTwoID");

                    b.HasIndex("MidfielderFiveID");

                    b.HasIndex("MidfielderFourID");

                    b.HasIndex("MidfielderOneID");

                    b.HasIndex("MidfielderThreeID");

                    b.HasIndex("MidfielderTwoID");

                    b.HasIndex("PersonID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("PlayerID1");

                    b.ToTable("FantasyTeams");

                    b.HasCheckConstraint("CHK_GoalieOne_Unique", "GoalieOneID <> GoalieTwoID AND \r\n									     GoalieOneID <> DefenderOneID AND\r\n										 GoalieOneID <> DefenderTwoID AND\r\n										 GoalieOneID <> DefenderThreeID AND\r\n										 GoalieOneID <> DefenderFourID AND\r\n										 GoalieOneID <> DefenderFiveID AND\r\n										 GoalieOneID <> MidfielderOneID AND\r\n										 GoalieOneID <> MidfielderTwoID AND\r\n										 GoalieOneID <> MidfielderThreeID AND\r\n										 GoalieOneID <> MidfielderFourID AND\r\n										 GoalieOneID <> MidfielderFiveID AND\r\n										 GoalieOneID <> ForwardOneID AND\r\n										 GoalieOneID <> ForwardTwoID AND\r\n										 GoalieOneID <> ForwardThreeID");
                });

            modelBuilder.Entity("Domain.Formation", b =>
                {
                    b.Property<Guid>("FormationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefenderCount")
                        .HasColumnType("int");

                    b.Property<string>("FormationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForwardCount")
                        .HasColumnType("int");

                    b.Property<int>("MidfielderCount")
                        .HasColumnType("int");

                    b.HasKey("FormationID");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("Domain.League", b =>
                {
                    b.Property<Guid>("LeagueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("APIFootballID")
                        .HasColumnType("int");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeagueLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeagueID");

                    b.HasIndex("CountryID");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Domain.Matchday", b =>
                {
                    b.Property<Guid>("MatchdayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MatchdayCount")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MatchdayID");

                    b.HasIndex("LeagueID");

                    b.ToTable("Matchdays");
                });

            modelBuilder.Entity("Domain.MatchdayTeam", b =>
                {
                    b.Property<Guid>("MatchdayTeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BenchOneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BenchThreeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BenchTwoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GoalieID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchdayTeamConfigurationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerEightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerFiveID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerFourID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerNineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlayerNinePlayerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerOneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerSevenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerSixID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerTenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerThreeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerTwoID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchdayTeamID");

                    b.HasIndex("BenchOneID");

                    b.HasIndex("BenchThreeID");

                    b.HasIndex("BenchTwoID");

                    b.HasIndex("GoalieID");

                    b.HasIndex("PlayerFiveID");

                    b.HasIndex("PlayerFourID");

                    b.HasIndex("PlayerNineID");

                    b.HasIndex("PlayerNinePlayerID");

                    b.HasIndex("PlayerOneID");

                    b.HasIndex("PlayerSevenID");

                    b.HasIndex("PlayerSixID");

                    b.HasIndex("PlayerTenID");

                    b.HasIndex("PlayerThreeID");

                    b.HasIndex("PlayerTwoID");

                    b.ToTable("MatchdayTeams");
                });

            modelBuilder.Entity("Domain.MatchdayTeamConfiguration", b =>
                {
                    b.Property<Guid>("MatchdayTeamConfigurationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaptainID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FantasyTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchdayID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchdayTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MatchdayTeamConfigurationID");

                    b.HasIndex("CaptainID");

                    b.HasIndex("FantasyTeamID");

                    b.HasIndex("FormationID");

                    b.HasIndex("MatchdayID");

                    b.HasIndex("MatchdayTeamID")
                        .IsUnique();

                    b.ToTable("MatchdayTeamConfigurations");
                });

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonID");

                    b.HasIndex("CountryID");

                    b.HasIndex("TeamID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Domain.Player", b =>
                {
                    b.Property<Guid>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("APIFootballID")
                        .HasColumnType("int");

                    b.Property<Guid>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("Injured")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("CountryID");

                    b.HasIndex("TeamID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Domain.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("APIFootballID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeamLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.HasIndex("LeagueID")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirebaseID")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.FantasyLeagueAdmin", b =>
                {
                    b.HasOne("Domain.FantasyLeague", "FantasyLeague")
                        .WithMany("FantasyLeagueAdmins")
                        .HasForeignKey("FantasyLeagueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Person", "Person")
                        .WithMany("FantasyLeagueAdmins")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyLeague");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.FantasyLeagueTeams", b =>
                {
                    b.HasOne("Domain.FantasyLeague", "FantasyLeague")
                        .WithMany("FantasyLeagueTeams")
                        .HasForeignKey("FantasyLeagueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.FantasyTeam", "FantasyTeam")
                        .WithMany("FantasyLeagueTeams")
                        .HasForeignKey("FantasyTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyLeague");

                    b.Navigation("FantasyTeam");
                });

            modelBuilder.Entity("Domain.FantasyTeam", b =>
                {
                    b.HasOne("Domain.Player", "DefenderFive")
                        .WithMany("DefenderFiveFantasyTeams")
                        .HasForeignKey("DefenderFiveID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "DefenderFour")
                        .WithMany("DefenderFourFantasyTeams")
                        .HasForeignKey("DefenderFourID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "DefenderOne")
                        .WithMany("DefenderOneFantasyTeams")
                        .HasForeignKey("DefenderOneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "DefenderThree")
                        .WithMany("DefenderThreeFantasyTeams")
                        .HasForeignKey("DefenderThreeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "DefenderTwo")
                        .WithMany("DefenderTwoFantasyTeams")
                        .HasForeignKey("DefenderTwoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "ForwardOne")
                        .WithMany("ForwardOneFantasyTeams")
                        .HasForeignKey("ForwardOneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "ForwardThree")
                        .WithMany("ForwardThreeFantasyTeams")
                        .HasForeignKey("ForwardThreeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "ForwardTwo")
                        .WithMany("ForwardTwoFantasyTeams")
                        .HasForeignKey("ForwardTwoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "GoalieOne")
                        .WithMany("GoalieOneFantasyTeams")
                        .HasForeignKey("GoalieOneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "GoalieTwo")
                        .WithMany("GoalieTwoFantasyTeams")
                        .HasForeignKey("GoalieTwoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "MidfielderFive")
                        .WithMany("MidfielderFiveFantasyTeams")
                        .HasForeignKey("MidfielderFiveID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "MidfielderFour")
                        .WithMany("MidfielderFourFantasyTeams")
                        .HasForeignKey("MidfielderFourID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "MidfielderOne")
                        .WithMany("MidfielderOneFantasyTeams")
                        .HasForeignKey("MidfielderOneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "MidfielderThree")
                        .WithMany("MidfielderThreeFantasyTeams")
                        .HasForeignKey("MidfielderThreeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "MidfielderTwo")
                        .WithMany("MidfielderTwoFantasyTeams")
                        .HasForeignKey("MidfielderTwoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Person", "Person")
                        .WithMany("FantasyTeams")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Player", null)
                        .WithMany("ForwardFiveFantasyTeams")
                        .HasForeignKey("PlayerID");

                    b.HasOne("Domain.Player", null)
                        .WithMany("ForwardFourFantasyTeams")
                        .HasForeignKey("PlayerID1");

                    b.Navigation("DefenderFive");

                    b.Navigation("DefenderFour");

                    b.Navigation("DefenderOne");

                    b.Navigation("DefenderThree");

                    b.Navigation("DefenderTwo");

                    b.Navigation("ForwardOne");

                    b.Navigation("ForwardThree");

                    b.Navigation("ForwardTwo");

                    b.Navigation("GoalieOne");

                    b.Navigation("GoalieTwo");

                    b.Navigation("MidfielderFive");

                    b.Navigation("MidfielderFour");

                    b.Navigation("MidfielderOne");

                    b.Navigation("MidfielderThree");

                    b.Navigation("MidfielderTwo");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.League", b =>
                {
                    b.HasOne("Domain.Country", "Country")
                        .WithMany("League")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Matchday", b =>
                {
                    b.HasOne("Domain.League", "League")
                        .WithMany("MatchDays")
                        .HasForeignKey("LeagueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Domain.MatchdayTeam", b =>
                {
                    b.HasOne("Domain.Player", "BenchOne")
                        .WithMany("BenchOneMatchdayTeams")
                        .HasForeignKey("BenchOneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "BenchThree")
                        .WithMany("BenchThreeMatchdayTeams")
                        .HasForeignKey("BenchThreeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "BenchTwo")
                        .WithMany("BenchTwoMatchdayTeams")
                        .HasForeignKey("BenchTwoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "Goalie")
                        .WithMany("GoalieMatchdayTeams")
                        .HasForeignKey("GoalieID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerFive")
                        .WithMany("PlayerFiveMatchdayTeams")
                        .HasForeignKey("PlayerFiveID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerFour")
                        .WithMany("PlayerFourMatchdayTeams")
                        .HasForeignKey("PlayerFourID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerEight")
                        .WithMany("PlayerEightMatchdayTeams")
                        .HasForeignKey("PlayerNineID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerNine")
                        .WithMany("PlayerNineMatchdayTeams")
                        .HasForeignKey("PlayerNinePlayerID");

                    b.HasOne("Domain.Player", "PlayerOne")
                        .WithMany("PlayerOneMatchdayTeams")
                        .HasForeignKey("PlayerOneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerSeven")
                        .WithMany("PlayerSevenMatchdayTeams")
                        .HasForeignKey("PlayerSevenID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerSix")
                        .WithMany("PlayerSixMatchdayTeams")
                        .HasForeignKey("PlayerSixID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerTen")
                        .WithMany("PlayerTenMatchdayTeams")
                        .HasForeignKey("PlayerTenID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerThree")
                        .WithMany("PlayerThreeMatchdayTeams")
                        .HasForeignKey("PlayerThreeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Player", "PlayerTwo")
                        .WithMany("PlayerTwoMatchdayTeams")
                        .HasForeignKey("PlayerTwoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BenchOne");

                    b.Navigation("BenchThree");

                    b.Navigation("BenchTwo");

                    b.Navigation("Goalie");

                    b.Navigation("PlayerEight");

                    b.Navigation("PlayerFive");

                    b.Navigation("PlayerFour");

                    b.Navigation("PlayerNine");

                    b.Navigation("PlayerOne");

                    b.Navigation("PlayerSeven");

                    b.Navigation("PlayerSix");

                    b.Navigation("PlayerTen");

                    b.Navigation("PlayerThree");

                    b.Navigation("PlayerTwo");
                });

            modelBuilder.Entity("Domain.MatchdayTeamConfiguration", b =>
                {
                    b.HasOne("Domain.Player", "Player")
                        .WithMany("MatchdayTeamConfiguration")
                        .HasForeignKey("CaptainID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.FantasyTeam", "FantasyTeam")
                        .WithMany("MatchdayTeamConfiguration")
                        .HasForeignKey("FantasyTeamID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Formation", "Formation")
                        .WithMany("MatchdayTeamConfiguration")
                        .HasForeignKey("FormationID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Matchday", "Matchday")
                        .WithMany("MatchdayTeamConfiguration")
                        .HasForeignKey("MatchdayID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.MatchdayTeam", "MatchdayTeam")
                        .WithOne("MatchdayTeamConfiguration")
                        .HasForeignKey("Domain.MatchdayTeamConfiguration", "MatchdayTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Formation");

                    b.Navigation("Matchday");

                    b.Navigation("MatchdayTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.HasOne("Domain.Country", "Country")
                        .WithMany("Person")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Team", "Team")
                        .WithMany("Person")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Player", b =>
                {
                    b.HasOne("Domain.Country", "Country")
                        .WithMany("Player")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Team", "Team")
                        .WithMany("Player")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Team", b =>
                {
                    b.HasOne("Domain.League", "League")
                        .WithOne("Team")
                        .HasForeignKey("Domain.Team", "LeagueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.HasOne("Domain.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Domain.User", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Country", b =>
                {
                    b.Navigation("League");

                    b.Navigation("Person");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Domain.FantasyLeague", b =>
                {
                    b.Navigation("FantasyLeagueAdmins");

                    b.Navigation("FantasyLeagueTeams");
                });

            modelBuilder.Entity("Domain.FantasyTeam", b =>
                {
                    b.Navigation("FantasyLeagueTeams");

                    b.Navigation("MatchdayTeamConfiguration");
                });

            modelBuilder.Entity("Domain.Formation", b =>
                {
                    b.Navigation("MatchdayTeamConfiguration");
                });

            modelBuilder.Entity("Domain.League", b =>
                {
                    b.Navigation("MatchDays");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Matchday", b =>
                {
                    b.Navigation("MatchdayTeamConfiguration");
                });

            modelBuilder.Entity("Domain.MatchdayTeam", b =>
                {
                    b.Navigation("MatchdayTeamConfiguration");
                });

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.Navigation("FantasyLeagueAdmins");

                    b.Navigation("FantasyTeams");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Player", b =>
                {
                    b.Navigation("BenchOneMatchdayTeams");

                    b.Navigation("BenchThreeMatchdayTeams");

                    b.Navigation("BenchTwoMatchdayTeams");

                    b.Navigation("DefenderFiveFantasyTeams");

                    b.Navigation("DefenderFourFantasyTeams");

                    b.Navigation("DefenderOneFantasyTeams");

                    b.Navigation("DefenderThreeFantasyTeams");

                    b.Navigation("DefenderTwoFantasyTeams");

                    b.Navigation("ForwardFiveFantasyTeams");

                    b.Navigation("ForwardFourFantasyTeams");

                    b.Navigation("ForwardOneFantasyTeams");

                    b.Navigation("ForwardThreeFantasyTeams");

                    b.Navigation("ForwardTwoFantasyTeams");

                    b.Navigation("GoalieMatchdayTeams");

                    b.Navigation("GoalieOneFantasyTeams");

                    b.Navigation("GoalieTwoFantasyTeams");

                    b.Navigation("MatchdayTeamConfiguration");

                    b.Navigation("MidfielderFiveFantasyTeams");

                    b.Navigation("MidfielderFourFantasyTeams");

                    b.Navigation("MidfielderOneFantasyTeams");

                    b.Navigation("MidfielderThreeFantasyTeams");

                    b.Navigation("MidfielderTwoFantasyTeams");

                    b.Navigation("PlayerEightMatchdayTeams");

                    b.Navigation("PlayerFiveMatchdayTeams");

                    b.Navigation("PlayerFourMatchdayTeams");

                    b.Navigation("PlayerNineMatchdayTeams");

                    b.Navigation("PlayerOneMatchdayTeams");

                    b.Navigation("PlayerSevenMatchdayTeams");

                    b.Navigation("PlayerSixMatchdayTeams");

                    b.Navigation("PlayerTenMatchdayTeams");

                    b.Navigation("PlayerThreeMatchdayTeams");

                    b.Navigation("PlayerTwoMatchdayTeams");
                });

            modelBuilder.Entity("Domain.Team", b =>
                {
                    b.Navigation("Person");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
