using Microsoft.EntityFrameworkCore.Migrations;

namespace Persistence.Migrations
{
    public partial class AddedCheckConstraintsforallPlayersColumnsinFantasyTeamTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "CHK_GoalieOne_Unique",
                table: "FantasyTeams");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_GoalieOne_Unique",
                table: "FantasyTeams",
                sql: "GoalieOneID <> GoalieTwoID AND \r\n									                                                                       GoalieOneID <> DefenderOneID AND\r\n										                                                                   GoalieOneID <> DefenderTwoID AND\r\n										                                                                   GoalieOneID <> DefenderThreeID AND\r\n										                                                                   GoalieOneID <> DefenderFourID AND\r\n										                                                                   GoalieOneID <> DefenderFiveID AND\r\n										                                                                   GoalieOneID <> MidfielderOneID AND\r\n										                                                                   GoalieOneID <> MidfielderTwoID AND\r\n										                                                                   GoalieOneID <> MidfielderThreeID AND\r\n										                                                                   GoalieOneID <> MidfielderFourID AND\r\n										                                                                   GoalieOneID <> MidfielderFiveID AND\r\n										                                                                   GoalieOneID <> ForwardOneID AND\r\n										                                                                   GoalieOneID <> ForwardTwoID AND\r\n										                                                                   GoalieOneID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_GoalieTwo_Unique",
                table: "FantasyTeams",
                sql: "GoalieTwoID <> GoalieOneID AND \r\n                                                                                                           GoalieTwoID <> DefenderOneID AND\r\n                                                                                                           GoalieTwoID <> DefenderTwoID AND\r\n                                                                                                           GoalieTwoID <> DefenderThreeID AND\r\n                                                                                                           GoalieTwoID <> DefenderFourID AND\r\n                                                                                                           GoalieTwoID <> DefenderFiveID AND\r\n                                                                                                           GoalieTwoID <> MidfielderOneID AND\r\n                                                                                                           GoalieTwoID <> MidfielderTwoID AND\r\n                                                                                                           GoalieTwoID <> MidfielderThreeID AND\r\n                                                                                                           GoalieTwoID <> MidfielderFourID AND\r\n                                                                                                           GoalieTwoID <> MidfielderFiveID AND\r\n                                                                                                           GoalieTwoID <> ForwardOneID AND\r\n                                                                                                           GoalieTwoID <> ForwardTwoID AND\r\n                                                                                                           GoalieTwoID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_DefenderOne_Unique",
                table: "FantasyTeams",
                sql: "DefenderOneID <> GoalieTwoID AND \r\n                                                                                                             DefenderOneID <> GoallieOneID AND\r\n                                                                                                             DefenderOneID <> DefenderTwoID AND\r\n                                                                                                             DefenderOneID <> DefenderThreeID AND\r\n                                                                                                             DefenderOneID <> DefenderFourID AND\r\n                                                                                                             DefenderOneID <> DefenderFiveID AND\r\n                                                                                                             DefenderOneID <> MidfielderOneID AND\r\n                                                                                                             DefenderOneID <> MidfielderTwoID AND\r\n                                                                                                             DefenderOneID <> MidfielderThreeID AND\r\n                                                                                                             DefenderOneID <> MidfielderFourID AND\r\n                                                                                                             DefenderOneID <> MidfielderFiveID AND\r\n                                                                                                             DefenderOneID <> ForwardOneID AND\r\n                                                                                                             DefenderOneID <> ForwardTwoID AND\r\n                                                                                                             DefenderOneID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_DefenderTwo_Unique",
                table: "FantasyTeams",
                sql: "DefenderTwoID <> GoalieTwoID AND \r\n                                                                                                             DefenderTwoID <> DefenderOneID AND\r\n                                                                                                             DefenderTwoID <> GoalieOneID AND\r\n                                                                                                             DefenderTwoID <> DefenderThreeID AND\r\n                                                                                                             DefenderTwoID <> DefenderFourID AND\r\n                                                                                                             DefenderTwoID <> DefenderFiveID AND\r\n                                                                                                             DefenderTwoID <> MidfielderOneID AND\r\n                                                                                                             DefenderTwoID <> MidfielderTwoID AND\r\n                                                                                                             DefenderTwoID <> MidfielderThreeID AND\r\n                                                                                                             DefenderTwoID <> MidfielderFourID AND\r\n                                                                                                             DefenderTwoID <> MidfielderFiveID AND\r\n                                                                                                             DefenderTwoID <> ForwardOneID AND\r\n                                                                                                             DefenderTwoID <> ForwardTwoID AND\r\n                                                                                                             DefenderTwoID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_DefenderThree_Unique",
                table: "FantasyTeams",
                sql: "DefenderThreeID <> GoalieTwoID AND \r\n                                                                                                               DefenderThreeID <> DefenderOneID AND\r\n                                                                                                               DefenderThreeID <> DefenderTwoID AND\r\n                                                                                                               DefenderThreeID <> GoalieOneID AND\r\n                                                                                                               DefenderThreeID <> DefenderFourID AND\r\n                                                                                                               DefenderThreeID <> DefenderFiveID AND\r\n                                                                                                               DefenderThreeID <> MidfielderOneID AND\r\n                                                                                                               DefenderThreeID <> MidfielderTwoID AND\r\n                                                                                                               DefenderThreeID <> MidfielderThreeID AND\r\n                                                                                                               DefenderThreeID <> MidfielderFourID AND\r\n                                                                                                               DefenderThreeID <> MidfielderFiveID AND\r\n                                                                                                               DefenderThreeID <> ForwardOneID AND\r\n                                                                                                               DefenderThreeID <> ForwardTwoID AND\r\n                                                                                                               DefenderThreeID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_DefenderFour_Unique",
                table: "FantasyTeams",
                sql: "DefenderFourID <> GoalieTwoID AND \r\n                                                                                                              DefenderFourID <> DefenderOneID AND\r\n                                                                                                              DefenderFourID <> DefenderTwoID AND\r\n                                                                                                              DefenderFourID <> GoalieOneID AND\r\n                                                                                                              DefenderFourID <> DefenderThreeID AND\r\n                                                                                                              DefenderFourID <> DefenderFiveID AND\r\n                                                                                                              DefenderFourID <> MidfielderOneID AND\r\n                                                                                                              DefenderFourID <> MidfielderTwoID AND\r\n                                                                                                              DefenderFourID <> MidfielderThreeID AND\r\n                                                                                                              DefenderFourID <> MidfielderFourID AND\r\n                                                                                                              DefenderFourID <> MidfielderFiveID AND\r\n                                                                                                              DefenderFourID <> ForwardOneID AND\r\n                                                                                                              DefenderFourID <> ForwardTwoID AND\r\n                                                                                                              DefenderFourID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_DefenderFive_Unique",
                table: "FantasyTeams",
                sql: "DefenderFiveID <> GoalieTwoID AND \r\n                                                                                                              DefenderFiveID <> DefenderOneID AND\r\n                                                                                                              DefenderFiveID <> DefenderTwoID AND\r\n                                                                                                              DefenderFiveID <> DefenderThreeID AND\r\n                                                                                                              DefenderFiveID <> DefenderFourID AND\r\n                                                                                                              DefenderFiveID <> GoalieOneID AND\r\n                                                                                                              DefenderFiveID <> MidfielderOneID AND\r\n                                                                                                              DefenderFiveID <> MidfielderTwoID AND\r\n                                                                                                              DefenderFiveID <> MidfielderThreeID AND\r\n                                                                                                              DefenderFiveID <> MidfielderFourID AND\r\n                                                                                                              DefenderFiveID <> MidfielderFiveID AND\r\n                                                                                                              DefenderFiveID <> ForwardOneID AND\r\n                                                                                                              DefenderFiveID <> ForwardTwoID AND\r\n                                                                                                              DefenderFiveID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_MidfielderOne_Unique",
                table: "FantasyTeams",
                sql: "MidfielderOneID <> GoalieOneID AND \r\n                                                                                                               MidfielderOneID <> DefenderOneID AND\r\n                                                                                                               MidfielderOneID <> DefenderTwoID AND\r\n                                                                                                               MidfielderOneID <> DefenderThreeID AND\r\n                                                                                                               MidfielderOneID <> DefenderFourID AND\r\n                                                                                                               MidfielderOneID <> DefenderFiveID AND\r\n                                                                                                               MidfielderOneID <> GoalieTwoID AND\r\n                                                                                                               MidfielderOneID <> MidfielderTwoID AND\r\n                                                                                                               MidfielderOneID <> MidfielderThreeID AND\r\n                                                                                                               MidfielderOneID <> MidfielderFourID AND\r\n                                                                                                               MidfielderOneID <> MidfielderFiveID AND\r\n                                                                                                               MidfielderOneID <> ForwardOneID AND\r\n                                                                                                               MidfielderOneID <> ForwardTwoID AND\r\n                                                                                                               MidfielderOneID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_MidfielderTwo_Unique",
                table: "FantasyTeams",
                sql: "MidfielderTwoID <> GoalieTwoID AND \r\n                                                                                                               MidfielderTwoID <> GoallieOneID AND\r\n                                                                                                               MidfielderTwoID <> DefenderTwoID AND\r\n                                                                                                               MidfielderTwoID <> DefenderThreeID AND\r\n                                                                                                               MidfielderTwoID <> DefenderFourID AND\r\n                                                                                                               MidfielderTwoID <> DefenderFiveID AND\r\n                                                                                                               MidfielderTwoID <> MidfielderOneID AND\r\n                                                                                                               MidfielderTwoID <> DefenderOneID AND\r\n                                                                                                               MidfielderTwoID <> MidfielderThreeID AND\r\n                                                                                                               MidfielderTwoID <> MidfielderFourID AND\r\n                                                                                                               MidfielderTwoID <> MidfielderFiveID AND\r\n                                                                                                               MidfielderTwoID <> ForwardOneID AND\r\n                                                                                                               MidfielderTwoID <> ForwardTwoID AND\r\n                                                                                                               MidfielderTwoID <> ForwardThreeID)");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_MidfielderThree_Unique",
                table: "FantasyTeams",
                sql: "MidfielderThreeID <> GoalieOneID AND \r\n                                                                                                               MidfielderThreeID <> DefenderOneID AND\r\n                                                                                                               MidfielderThreeID <> DefenderTwoID AND\r\n                                                                                                               MidfielderThreeID <> DefenderThreeID AND\r\n                                                                                                               MidfielderThreeID <> DefenderFourID AND\r\n                                                                                                               MidfielderThreeID <> DefenderFiveID AND\r\n                                                                                                               MidfielderThreeID <> GoalieTwoID AND\r\n                                                                                                               MidfielderThreeID <> MidfielderTwoID AND\r\n                                                                                                               MidfielderThreeID <> MidfielderOneID AND\r\n                                                                                                               MidfielderThreeID <> MidfielderFourID AND\r\n                                                                                                               MidfielderThreeID <> MidfielderFiveID AND\r\n                                                                                                               MidfielderThreeID <> ForwardOneID AND\r\n                                                                                                               MidfielderThreeID <> ForwardTwoID AND\r\n                                                                                                               MidfielderThreeID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_MidfielderFour_Unique",
                table: "FantasyTeams",
                sql: "MidfielderFourID <> GoalieTwoID AND \r\n                                                                                                                MidfielderFourID <> DefenderOneID AND\r\n                                                                                                                MidfielderFourID <> DefenderTwoID AND\r\n                                                                                                                MidfielderFourID <> GoalieOneID AND\r\n                                                                                                                MidfielderFourID <> DefenderFourID AND\r\n                                                                                                                MidfielderFourID <> DefenderFiveID AND\r\n                                                                                                                MidfielderFourID <> MidfielderOneID AND\r\n                                                                                                                MidfielderFourID <> MidfielderTwoID AND\r\n                                                                                                                MidfielderFourID <> MidfielderThreeID AND\r\n                                                                                                                MidfielderFourID <> DefenderThreeID AND\r\n                                                                                                                MidfielderFourID <> MidfielderFiveID AND\r\n                                                                                                                MidfielderFourID <> ForwardOneID AND\r\n                                                                                                                MidfielderFourID <> ForwardTwoID AND\r\n                                                                                                                MidfielderFourID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_MidfielderFive_Unique",
                table: "FantasyTeams",
                sql: "MidfielderFiveID <> GoalieTwoID AND \r\n                                                                                                                MidfielderFiveID <> DefenderOneID AND\r\n                                                                                                                MidfielderFiveID <> DefenderTwoID AND\r\n                                                                                                                MidfielderFiveID <> GoalieOneID AND\r\n                                                                                                                MidfielderFiveID <> DefenderFourID AND\r\n                                                                                                                MidfielderFiveID <> DefenderFiveID AND\r\n                                                                                                                MidfielderFiveID <> MidfielderOneID AND\r\n                                                                                                                MidfielderFiveID <> MidfielderTwoID AND\r\n                                                                                                                MidfielderFiveID <> MidfielderThreeID AND\r\n                                                                                                                MidfielderFiveID <> MidfielderFourID AND\r\n                                                                                                                MidfielderFiveID <> DefenderThreeID AND\r\n                                                                                                                MidfielderFiveID <> ForwardOneID AND\r\n                                                                                                                MidfielderFiveID <> ForwardTwoID AND\r\n                                                                                                                MidfielderFiveID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_ForwardOne_Unique",
                table: "FantasyTeams",
                sql: "ForwardOneID <> GoalieTwoID AND \r\n                                                                                                            ForwardOneID <> DefenderOneID AND\r\n                                                                                                            ForwardOneID <> DefenderTwoID AND\r\n                                                                                                            ForwardOneID <> DefenderThreeID AND\r\n                                                                                                            ForwardOneID <> DefenderFourID AND\r\n                                                                                                            ForwardOneID <> DefenderFiveID AND\r\n                                                                                                            ForwardOneID <> MidfielderOneID AND\r\n                                                                                                            ForwardOneID <> MidfielderTwoID AND\r\n                                                                                                            ForwardOneID <> MidfielderThreeID AND\r\n                                                                                                            ForwardOneID <> MidfielderFourID AND\r\n                                                                                                            ForwardOneID <> MidfielderFiveID AND\r\n                                                                                                            ForwardOneID <> GoalieOneID AND\r\n                                                                                                            ForwardOneID <> ForwardTwoID AND\r\n                                                                                                            ForwardOneID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_ForwardTwo_Unique",
                table: "FantasyTeams",
                sql: "ForwardTwoID <> GoalieOneID AND \r\n                                                                                                            ForwardTwoID <> DefenderOneID AND\r\n                                                                                                            ForwardTwoID <> DefenderTwoID AND\r\n                                                                                                            ForwardTwoID <> DefenderThreeID AND\r\n                                                                                                            ForwardTwoID <> DefenderFourID AND\r\n                                                                                                            ForwardTwoID <> DefenderFiveID AND\r\n                                                                                                            ForwardTwoID <> MidfielderOneID AND\r\n                                                                                                            ForwardTwoID <> MidfielderTwoID AND\r\n                                                                                                            ForwardTwoID <> MidfielderThreeID AND\r\n                                                                                                            ForwardTwoID <> MidfielderFourID AND\r\n                                                                                                            ForwardTwoID <> MidfielderFiveID AND\r\n                                                                                                            ForwardTwoID <> ForwardOneID AND\r\n                                                                                                            ForwardTwoID <> GoalieTwoID AND\r\n                                                                                                            ForwardTwoID <> ForwardThreeID");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_ForwardThree_Unique",
                table: "FantasyTeams",
                sql: "ForwardThreeID <> GoalieTwoID AND \r\n                                                                                                              ForwardThreeID <> GoallieOneID AND\r\n                                                                                                              ForwardThreeID <> DefenderTwoID AND\r\n                                                                                                              ForwardThreeID <> DefenderThreeID AND\r\n                                                                                                              ForwardThreeID <> DefenderFourID AND\r\n                                                                                                              ForwardThreeID <> DefenderFiveID AND\r\n                                                                                                              ForwardThreeID <> MidfielderOneID AND\r\n                                                                                                              ForwardThreeID <> MidfielderTwoID AND\r\n                                                                                                              ForwardThreeID <> MidfielderThreeID AND\r\n                                                                                                              ForwardThreeID <> MidfielderFourID AND\r\n                                                                                                              ForwardThreeID <> MidfielderFiveID AND\r\n                                                                                                              ForwardThreeID <> ForwardOneID AND\r\n                                                                                                              ForwardThreeID <> ForwardTwoID AND\r\n                                                                                                              ForwardThreeID <> DefenderOneID");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "CHK_GoalieOne_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_GoalieTwo_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_DefenderOne_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_DefenderTwo_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_DefenderThree_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_DefenderFour_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_DefenderFive_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_MidfielderOne_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_MidfielderTwo_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_MidfielderThree_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_MidfielderFour_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_MidfielderFive_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_ForwardOne_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_ForwardTwo_Unique",
                table: "FantasyTeams");

            migrationBuilder.DropCheckConstraint(
                name: "CHK_ForwardThree_Unique",
                table: "FantasyTeams");

            migrationBuilder.AddCheckConstraint(
                name: "CHK_GoalieOne_Unique",
                table: "FantasyTeams",
                sql: "GoalieOneID <> GoalieTwoID AND \r\n									     GoalieOneID <> DefenderOneID AND\r\n										 GoalieOneID <> DefenderTwoID AND\r\n										 GoalieOneID <> DefenderThreeID AND\r\n										 GoalieOneID <> DefenderFourID AND\r\n										 GoalieOneID <> DefenderFiveID AND\r\n										 GoalieOneID <> MidfielderOneID AND\r\n										 GoalieOneID <> MidfielderTwoID AND\r\n										 GoalieOneID <> MidfielderThreeID AND\r\n										 GoalieOneID <> MidfielderFourID AND\r\n										 GoalieOneID <> MidfielderFiveID AND\r\n										 GoalieOneID <> ForwardOneID AND\r\n										 GoalieOneID <> ForwardTwoID AND\r\n										 GoalieOneID <> ForwardThreeID");
        }
    }
}
